import 'package:flutter/material.dart';

const List<IconData> DEFAULT_ICONS = [
  Icons.account_balance_wallet,
  Icons.account_box,
  Icons.archive,
  Icons.attachment,
  Icons.battery_charging_full,
  Icons.book,
  Icons.brush,
  Icons.build,
  Icons.color_lens,
  Icons.desktop_windows,
  Icons.content_cut,
  Icons.create,
  Icons.credit_card,
  Icons.devices_other,
  Icons.dns,
  Icons.format_paint,
  Icons.headset,
  Icons.image,
  Icons.local_florist,
  Icons.pets,
  Icons.photo_camera,
  Icons.restaurant,
  Icons.security,
  Icons.style,
  Icons.straighten,
  Icons.toys,
  Icons.videogame_asset,
];
